services:
  - type: web
    name: ocr-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    scaling:
      minInstances: 1
      maxInstances: 1 